import { Component, ViewEncapsulation } from '@angular/core';
import { GsapAnimationBase } from './gsap-animation.base';

@Component({
  selector: 'app-tfo-cookie',
  encapsulation: ViewEncapsulation.None,
  styles: `
    .tk-wrap {
      margin: 1.5rem 0;
      background: linear-gradient(180deg, #0f1729 0%, #0a0e17 100%);
      border-radius: 14px;
      border: 1px solid var(--border-color);
      padding: 1.75rem;
      overflow: hidden;
    }
    .tk-wrap svg { width: 100%; height: auto; display: block; }
  `,
  template: `
    <div class="tk-wrap">
      <svg viewBox="0 0 720 340" preserveAspectRatio="xMidYMid meet">
        <defs>
          <marker id="tk-arr-o" markerWidth="7" markerHeight="7" refX="6" refY="3" orient="auto">
            <polygon points="0 0,7 3,0 6" fill="#f59e0b"/>
          </marker>
          <marker id="tk-arr-g" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto">
            <polygon points="0 0,7 3,0 6" fill="#10b981"/>
          </marker>
        </defs>

        <!-- ===== PHASE 1 PANEL ===== -->
        <g class="tk-p1box" opacity="0">
          <rect x="8" y="8" width="704" height="156" rx="10"
                fill="rgba(245,158,11,0.03)" stroke="rgba(245,158,11,0.3)" stroke-width="1.5"/>
        </g>

        <g class="tk-p1" opacity="0">
          <text x="24" y="29" fill="#f59e0b" font-size="9" font-weight="700"
                font-family="Inter, sans-serif">STEP 1 — FIRST CONNECTION: earn the cookie</text>

          <rect x="14" y="38" width="120" height="30" rx="6"
                fill="rgba(34,211,238,0.07)" stroke="rgba(34,211,238,0.5)" stroke-width="1"/>
          <text x="74" y="57" text-anchor="middle" fill="#94a3b8" font-size="8"
                font-weight="700" font-family="Inter, sans-serif">CLIENT</text>
          <rect x="586" y="38" width="120" height="30" rx="6"
                fill="rgba(167,139,250,0.07)" stroke="rgba(167,139,250,0.5)" stroke-width="1"/>
          <text x="646" y="57" text-anchor="middle" fill="#94a3b8" font-size="8"
                font-weight="700" font-family="Inter, sans-serif">SERVER</text>

          <line x1="74" y1="68" x2="74" y2="150" stroke="#22d3ee" stroke-width="1"
                stroke-dasharray="3,4" opacity="0.35"/>
          <line x1="646" y1="68" x2="646" y2="150" stroke="#a78bfa" stroke-width="1"
                stroke-dasharray="3,4" opacity="0.35"/>
        </g>

        <!-- Phase 1 arrows -->
        <g class="tk-p1seg" opacity="0">
          <line x1="76" y1="90" x2="644" y2="90" stroke="#f59e0b" stroke-width="1.8"
                marker-end="url(#tk-arr-o)"/>
          <text x="360" y="84" text-anchor="middle" fill="#fcd34d" font-size="7.5"
                font-weight="600" font-family="Inter, sans-serif">
            SYN &#8594; "send me a TFO cookie"
          </text>
        </g>
        <g class="tk-p1seg" opacity="0">
          <line x1="644" y1="118" x2="76" y2="118" stroke="#f59e0b" stroke-width="1.8"
                marker-end="url(#tk-arr-o)"/>
          <text x="360" y="112" text-anchor="middle" fill="#fcd34d" font-size="7.5"
                font-weight="600" font-family="Inter, sans-serif">
            &#8592; SYN-ACK + encrypted cookie (generated by the server)
          </text>
        </g>

        <!-- Cookie cached badge -->
        <g class="tk-cookie" opacity="0">
          <rect x="26" y="130" width="138" height="22" rx="6"
                fill="rgba(245,158,11,0.14)" stroke="#f59e0b" stroke-width="1.2"/>
          <circle cx="42" cy="141" r="6" fill="rgba(245,158,11,0.45)"/>
          <circle cx="40" cy="139" r="1.2" fill="#78350f"/>
          <circle cx="45" cy="142" r="1.2" fill="#78350f"/>
          <circle cx="43" cy="144" r="1.1" fill="#78350f"/>
          <text x="95" y="145" text-anchor="middle" fill="#fcd34d" font-size="7"
                font-weight="700" font-family="Inter, sans-serif">TFO cookie cached</text>
        </g>

        <text class="tk-p1note" opacity="0" x="438" y="145" text-anchor="middle" fill="#64748b"
              font-size="7" font-family="Inter, sans-serif">
          Standard 1.5 RTT handshake — this trip only earns the cookie, no app data yet
        </text>

        <!-- ===== PHASE 2 PANEL ===== -->
        <g class="tk-p2box" opacity="0">
          <rect x="8" y="172" width="704" height="160" rx="10"
                fill="rgba(16,185,129,0.03)" stroke="rgba(16,185,129,0.3)" stroke-width="1.5"/>
        </g>

        <g class="tk-p2" opacity="0">
          <text x="24" y="193" fill="#10b981" font-size="9" font-weight="700"
                font-family="Inter, sans-serif">STEP 2 — EVERY CONNECTION AFTER: fast open</text>

          <rect x="14" y="202" width="120" height="28" rx="6"
                fill="rgba(34,211,238,0.07)" stroke="rgba(34,211,238,0.5)" stroke-width="1"/>
          <text x="74" y="220" text-anchor="middle" fill="#94a3b8" font-size="8"
                font-weight="700" font-family="Inter, sans-serif">CLIENT</text>
          <rect x="586" y="202" width="120" height="28" rx="6"
                fill="rgba(167,139,250,0.07)" stroke="rgba(167,139,250,0.5)" stroke-width="1"/>
          <text x="646" y="220" text-anchor="middle" fill="#94a3b8" font-size="8"
                font-weight="700" font-family="Inter, sans-serif">SERVER</text>

          <line x1="74" y1="248" x2="74" y2="320" stroke="#22d3ee" stroke-width="1"
                stroke-dasharray="3,4" opacity="0.35"/>
          <line x1="646" y1="248" x2="646" y2="320" stroke="#a78bfa" stroke-width="1"
                stroke-dasharray="3,4" opacity="0.35"/>
        </g>

        <!-- Phase 2: client already holds the cookie -->
        <g class="tk-cookie2" opacity="0">
          <rect x="22" y="233" width="104" height="15" rx="4"
                fill="rgba(245,158,11,0.14)" stroke="rgba(245,158,11,0.55)" stroke-width="1"/>
          <text x="74" y="244" text-anchor="middle" fill="#fcd34d" font-size="6.2"
                font-weight="600" font-family="Inter, sans-serif">cookie from step 1</text>
        </g>

        <!-- Phase 2 arrow 1: SYN + cookie + DATA -->
        <g class="tk-p2a" opacity="0">
          <line x1="76" y1="272" x2="644" y2="272" stroke="#10b981" stroke-width="2.4"
                marker-end="url(#tk-arr-g)"/>
          <text x="360" y="266" text-anchor="middle" fill="#6ee7b7" font-size="7.5"
                font-weight="600" font-family="Inter, sans-serif">
            SYN + cookie + request DATA — all in the very first packet
          </text>
        </g>

        <!-- Validate badge -->
        <g class="tk-valid" opacity="0">
          <rect x="244" y="280" width="232" height="18" rx="6"
                fill="rgba(16,185,129,0.1)" stroke="rgba(16,185,129,0.4)" stroke-width="1"/>
          <text x="360" y="292" text-anchor="middle" fill="#10b981" font-size="7"
                font-weight="700" font-family="Inter, sans-serif">
            &#10003; cookie valid — client proven, SYN-flood safe
          </text>
        </g>

        <!-- Phase 2 arrow 2: SYN-ACK + RESPONSE -->
        <g class="tk-p2b" opacity="0">
          <line x1="644" y1="312" x2="76" y2="312" stroke="#10b981" stroke-width="2.4"
                marker-end="url(#tk-arr-g)"/>
          <text x="360" y="306" text-anchor="middle" fill="#6ee7b7" font-size="7.5"
                font-weight="600" font-family="Inter, sans-serif">
            &#8592; SYN-ACK + response DATA — the answer is already on its way back
          </text>
        </g>

        <text class="tk-p2note" opacity="0" x="360" y="327" text-anchor="middle" fill="#10b981"
              font-size="7" font-weight="700" font-family="Inter, sans-serif">
          Request answered in ~1 RTT — a full round-trip saved versus the normal handshake
        </text>

      </svg>
    </div>
  `,
})
export class TfoCookieComponent extends GsapAnimationBase {
  protected initAnimation(): void {
    const container = this.q('.tk-wrap');
    const tl = this.createScrollTimeline(container);

    // Phase 1
    tl.fromTo(this.q('.tk-p1box'), { opacity: 0 }, { opacity: 1, duration: 0.3 });
    tl.fromTo(this.q('.tk-p1'), { opacity: 0, y: -4 }, { opacity: 1, y: 0, duration: 0.4 }, '-=0.05');
    tl.fromTo(
      this.qa('.tk-p1seg'),
      { opacity: 0, x: -8 },
      { opacity: 1, x: 0, duration: 0.4, stagger: 0.4, ease: 'power2.out' },
      '+=0.15',
    );
    tl.fromTo(
      this.q('.tk-cookie'),
      { opacity: 0, scale: 0.8 },
      { opacity: 1, scale: 1, duration: 0.45, ease: 'back.out(2)', transformOrigin: 'center' },
      '+=0.1',
    );
    tl.fromTo(this.q('.tk-p1note'), { opacity: 0 }, { opacity: 1, duration: 0.35 }, '-=0.15');

    // Phase 2
    tl.fromTo(this.q('.tk-p2box'), { opacity: 0 }, { opacity: 1, duration: 0.3 }, '+=0.25');
    tl.fromTo(this.q('.tk-p2'), { opacity: 0, y: -4 }, { opacity: 1, y: 0, duration: 0.4 }, '-=0.05');
    tl.fromTo(
      this.q('.tk-cookie2'),
      { opacity: 0, scale: 0.8 },
      { opacity: 1, scale: 1, duration: 0.4, ease: 'back.out(2)', transformOrigin: 'center' },
      '+=0.05',
    );
    tl.fromTo(
      this.q('.tk-p2a'),
      { opacity: 0, x: -8 },
      { opacity: 1, x: 0, duration: 0.4, ease: 'power2.out' },
      '+=0.1',
    );
    tl.fromTo(
      this.q('.tk-valid'),
      { opacity: 0, scale: 0.92 },
      { opacity: 1, scale: 1, duration: 0.4, ease: 'back.out(1.6)', transformOrigin: 'center' },
      '+=0.1',
    );
    tl.fromTo(
      this.q('.tk-p2b'),
      { opacity: 0, x: 8 },
      { opacity: 1, x: 0, duration: 0.4, ease: 'power2.out' },
      '+=0.1',
    );
    tl.fromTo(this.q('.tk-p2note'), { opacity: 0, y: 4 }, { opacity: 1, y: 0, duration: 0.4 }, '+=0.1');
  }
}
